[package]
name = "worldgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polymap = { path = "../polymap" }

rand = { version = "*", features = ["small_rng"]}
noise = "*"

